name = "DStyle"
uuid = "420f571e-3331-4aa3-9b68-c78ef2d7caab"
authors = ["Demetrius Michael <arrrwalktheplank@gmail.com>"]
version = "1.0.0-DEV"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.12"
